version: 2
workflows:
  version: 2
  workflow:
    jobs:
      - test-3.8-mongo3
      - test-3.8-mongo5
      - test-3.10-mongo3
      - test-3.10-mongo5
      - test-3.11-mongo3
      - test-3.11-mongo5
      - test-3.11-mongo6
      - test-3.11-mongo7
      - test-3.12-mongo3
      - test-3.12-mongo5
      - test-3.12-mongo6
      - test-3.12-mongo7
      - test-3.13-mongo3
      - test-3.13-mongo5
      - test-3.13-mongo6
      - test-3.13-mongo7

defaults: &defaults
  working_directory: ~/code
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: pip install --user -r test-requirements.txt
    - run:
        name: Test
        command: pytest tests/
jobs:
  test-3.8-mongo3:
    <<: *defaults
    docker:
      - image: cimg/python:3.8
      - image: mongo:3.6.23
  test-3.8-mongo5:
    <<: *defaults
    docker:
      - image: cimg/python:3.8
      - image: mongo:5.0.23
  test-3.10-mongo3:
    <<: *defaults
    docker:
      - image: cimg/python:3.10
      - image: mongo:3.6.23
  test-3.10-mongo5:
    <<: *defaults
    docker:
      - image: cimg/python:3.10
      - image: mongo:5.0.23
  test-3.11-mongo3:
    <<: *defaults
    docker:
      - image: cimg/python:3.11
      - image: mongo:3.6.23
  test-3.11-mongo5:
    <<: *defaults
    docker:
      - image: cimg/python:3.11
      - image: mongo:5.0.23
  test-3.11-mongo6:
    <<: *defaults
    docker:
      - image: cimg/python:3.11
      - image: mongo:6.0.19
  test-3.11-mongo7:
    <<: *defaults
    docker:
      - image: cimg/python:3.11
      - image: mongo:7.0.16
  test-3.12-mongo3:
    <<: *defaults
    docker:
      - image: cimg/python:3.12
      - image: mongo:3.6.23
  test-3.12-mongo5:
    <<: *defaults
    docker:
      - image: cimg/python:3.12
      - image: mongo:5.0.23
  test-3.12-mongo6:
    <<: *defaults
    docker:
      - image: cimg/python:3.12
      - image: mongo:6.0.19
  test-3.12-mongo7:
    <<: *defaults
    docker:
      - image: cimg/python:3.12
      - image: mongo:7.0.16
  test-3.13-mongo3:
    <<: *defaults
    docker:
      - image: cimg/python:3.13
      - image: mongo:3.6.23
  test-3.13-mongo5:
    <<: *defaults
    docker:
      - image: cimg/python:3.13
      - image: mongo:5.0.23
  test-3.13-mongo6:
    <<: *defaults
    docker:
      - image: cimg/python:3.13
      - image: mongo:6.0.19
  test-3.13-mongo7:
    <<: *defaults
    docker:
      - image: cimg/python:3.13
      - image: mongo:7.0.16
