version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.10
      - test-3.11

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install --user -r test-requirements.txt
  - run:
      name: Test
      command: pytest tests/

jobs:
  test-3.10:
    <<: *defaults
    docker:
    - image: circleci/python:3.10
    - image: mongo:3.2.19
  test-3.11:
    <<: *defaults
    docker:
    - image: cimg/python:3.11
    - image: mongo:3.2.19
