version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.8
      - test-3.9
      - test-3.10

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install --user -r test-requirements.txt
  - run:
      name: Test
      command: nosetests

jobs:
  test-3.8:
    <<: *defaults
    docker:
    - image: circleci/python:3.8
    - image: mongo:3.2.19
  test-3.9:
    <<: *defaults
    docker:
    - image: circleci/python:3.9
    - image: mongo:3.2.19
  test-3.10:
    <<: *defaults
    docker:
    - image: circleci/python:3.10
    - image: mongo:3.2.19
