version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.11
      - test-3.12

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install --user -r test-requirements.txt
  - run:
      name: Test
      command: pytest tests/

jobs:
  test-3.11:
    <<: *defaults
    docker:
    - image: circleci/python:3.11
    - image: mongo:6.0.16
  test-3.12:
    <<: *defaults
    docker:
    - image: circleci/python:3.12
    - image: mongo:6.0.16